### ISSUE TITLE
Focus is not going to page.

### ISSUE THREAD

**Issue by MZmuda75** [deadmund/Custom-New-Tab#10]
In the newest version released Aug 14, the focus is going to the URL, not the first item on the new page.

**Comment by deadmund** [comment]
You're correct, please use version 2.1.1 on Firefox 40.  
https://addons.mozilla.org/en-US/firefox/addon/custom-new-tab/versions/

**Comment by MZmuda75** [comment]
I upgraded CNT to version 3, and that seems to be working.
Thanks!
- Z
