### ISSUE TITLE
Did not function in Firefox 41.0b9

### ISSUE THREAD

**Issue by makyen** [deadmund/Custom-New-Tab#12]
This add-on had no effect when installed in Firefox 41.0b9 (64 bit Firefox, Windows 7x64) and the add-on option's page changed to a URL.

**Comment by deadmund** [comment]
There is a small bug that if you try to run CNT 2.x on Firefox 41 it won't work.  Make sure you're updated to CNT 3.x on Firefox 41 (it should auto-update but sometimes it doesn't).  In Firefox, if you click the Hamburger menu -> addons -> extensions -> and then right click CNT, you can choose to "find updates" and it should auto-update to CNT 3.x as long as you're using Firefox 41+

If the problem persists in CNT 3.x + Firefox 41, then please open a new issue.
