### ISSUE TITLE
Lots of tabs are opened after closing the last tab if closeWindowWithLastTab is false

### ISSUE THREAD

**Issue by jingyu9575** [deadmund/Custom-New-Tab#15]
Custom New Tab 4.3, Firefox Dev 51.0a2

If I set closeWindowWithLastTab to false in about:config (so that the browser will open a new tab if the last tab is closed), a lot of duplicate tabs set in the addon will open after closing the last tab.

Swaping the following lines fixes it for me, maybe because removing the last about:newtab triggers a new tab.

    browser.tabs.remove(tab.id); // close the new tab that was opened
    browser.tabs.create({"url":url_data.cnt_url_pref, "active":true}); // open our own tab

Edit:

    browser.tabs.create({"url":url_data.cnt_url_pref, "active":true}); // open our own tab
    setTimeout(() => {
        browser.tabs.remove(tab.id); // close the new tab that was opened
    }, 0);

**Comment by deadmund** [comment]
I think I fixed this issue.  Checkout CNT version 4.7
