### ISSUE TITLE
Firefox 54.0.1 (64-bit) crashes sometimes with new tab

### ISSUE THREAD

**Issue by JohnBeton22** [deadmund/Custom-New-Tab#17]
Hello, since a few days after updating firefox, your plugin seems to make FF crash sometimes when the + icon is clicked to open a new tab.

Please find a crashlog attached. I'm happy to help out when necessa
[mozzilla-crash.txt](https://github.com/deadmund/Custom-New-Tab/files/1119085/mozzilla-crash.txt)
ry!

**Comment by einst3** [comment]
what version is the addon?

**Comment by deadmund** [comment]
I'm not convinced this was related to CNT.
