### ISSUE TITLE
add support for file:///

### ISSUE THREAD

**Issue by einst3** [deadmund/Custom-New-Tab#18]
please finish or add support for file:/// as i use a local html file for my common links and right now i just leave a tab open in ff it would be great as new tab. pleeeeaaaasssseee

**Comment by deadmund** [comment]
Unfortunately I cannot allow for local flies (file:///) because this behavior is no longer supported by Firefox.  You can complain to the Mozilla devs, who believe this feature is a security issue.

**Comment by einst3** [comment]
ps. is there a way to iterate the new ff tabs to see if file:// exists? also what about about:... ?

**Comment by deadmund** [comment]
@einst3 Yes, it is definitely possible to iterate through the existing tabs (in all windows if there are multiple) and identify any / all tabs that are showing a file://    or about:    url.  

However, it is not possible to load in a tab anything besides http:// and https://  addresses.  See the documentation: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/update  (look at updateproperties -> url

I'm confused by your question though.  What is the point of iterating through the tabs?

**Comment by einst3** [comment]
just wondering. you answered my question and thanks for the webextension url reference.

**Comment by einst3** [comment]
oh, i thought that you could make a jump.html page passing the file:// to the url and use that in a js in your jump page to redirect to the actual local file. just a thought.

**Comment by deadmund** [comment]
@einst3 Glad I could help!
