### ISSUE TITLE
 Firefox Multi-Account Containers extension won't work with CNT

### ISSUE THREAD

**Issue by siffegh** [deadmund/Custom-New-Tab#20]
New container tabs created with Firefox Multi-Account Containers (https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers) are just regular tabs if CNT is also installed.

**Comment by stoically** [comment]
Just some pointers how it might be possible to achieve container compatibility:

* Add `contextualIdenties` to the permissions
* Pass the `cookieStoreId` you get for `_tab` in `tabs.onUpdated` to the `tabs.create` function

**Comment by deadmund** [comment]
Please try again with the new version.  I think that it should work now when the new focus option is set to false.

**Comment by stoically** [comment]
Doing it with tabs.update works, yes. However: Firefox Versions before 57 don't set openerTabId for tabs opened by MiddleMouse or Ctrl+Left clicking on links. And in general not for MiddleMouse or Ctrl+Left clicking on certain menu-elements (forward, backward, home and reload button)

**Comment by deadmund** [comment]
@stoically I noticed that bug too just a minute ago and put a quick fix in.  I think it's fixed now (in CNT version 4.7)

**Comment by stoically** [comment]
Can confirm, that's a good way to solve it. Well done.
