### ISSUE TITLE
empty url bar on tabs openend by other applications

### ISSUE THREAD

**Issue by Chaquator** [deadmund/Custom-New-Tab#8]
when opening links form other applications, the url bar is blank when the option to make it blank is checked
you can press ESC and get the URL though, so no big priority to fix

EDIT: it actually creates a blank url from opening any webpage in a new tab and switching to it before it finishes loading

**Comment by deadmund** [comment]
This is a known bug, but thank you for reporting it.  Unfortunately, I cant
figure out a good way to fix it!

Feel free to look at the CNT source on github and solve the problem if
you're technically inclined!

**Comment by deadmund** [comment]
I think this is fixed in version 3.0.  Please try it out when Firefox 41.0 is released! In the mean time (for Firefox 40.0 please use CNT version 2.1.1 https://addons.mozilla.org/en-US/firefox/addon/custom-new-tab/versions/
